CREATE TABLE ESTADO(
    UF VARCHAR(2) NOT NULL PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    DDD VARCHAR(2) NOT NULL,
    FOREIGN KEY (DDD) REFERENCES CHIP(DDD)
);

CREATE TABLE CIDADE(
    IDCIDADE uuid DEFAULT uuid_generate_v4() NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    UF varchar(2) NOT NULL,
    FOREIGN KEY (UF) REFERENCES ESTADO(UF)

);

CREATE TABLE CLIENTE(
    IDCLIENTE uuid DEFAULT uuid_generate_v4() NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    LOGRADOURO VARCHAR(60) NOT NULL,
    NUMERO INTEGER NOT NULL,
    COMPLEMENTO INTEGER NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    IDCIDADE INTEGER NOT NULL,
    DATACADASTRO DATE NOT NULL,
    CANCELADO VARCHAR(1) NOT NULL,
    FOREIGN KEY (IDCIDADE) REFERENCES CIDADE(IDCIDADE)
);
