--ARQUIVO CONTENDO VIEWS E INDÍCES

--VW-1
CREATE OR REPLACE VIEW VW_1
AS SELECT PLANO.IDPLANO, PLANO.DESCRICAO,(SELECT COUNT(CHIP.DISPONIVEL) FROM CHIP WHERE DISPONIVEL = 'S') AS QUANT_PLANOS_ATIVOS, ((SELECT COUNT(CHIP.DISPONIVEL) FROM CHIP WHERE DISPONIVEL = 'S') * PLANO.VALOR) AS VALOR_TOTAL
FROM PLANO JOIN CHIP
ON PLANO.IDPLANO = CHIP.ID_PLANO;

--VW-3
CREATE OR REPLACE VIEW VW_3
AS 
SELECT CLIENTE.IDCLIENTE, CLIENTE.NOME, ESTADO.UF, CHIP.IDNUMERO,PLANO.DESCRICAO, (SELECT AUDITORIA.DATA_TERMINO - AUDITORIA.DATA_INICIO FROM AUDITORIA JOIN CLIENTE ON CLIENTE.IDCLIENTE = AUDITORIA.IDCLIENTE) AS TEMPO_DE_FIDELIDADE
FROM CLIENTE JOIN CIDADE
ON CLIENTE.IDCIDADE = CIDADE.IDCIDADE
JOIN ESTADO
ON ESTADO.UF = CIDADE.UF
JOIN CLIENTE_CHIP
ON CLIENTE.IDCLIENTE = CLIENTE_CHIP.IDCLIENTE
JOIN CHIP
ON CHIP.IDNUMERO = CLIENTE_CHIP.IDNUMERO
JOIN PLANO
ON CHIP.ID_PLANO = PLANO.IDPLANO